log_viewer/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import django
from django.urls import path, include
from .views import (log_json, log_viewer, test)

app_name = 'log_viewer'

if django.VERSION >= (2, 0):
    from django.urls import re_path
    urlpatterns = [
        re_path(r'^json/(?P<file_name>[\.\w-]*)/(?P<page>[0-9]+)', log_json, name='log_json_view'),
        re_path(r'^json/(?P<file_name>[\.\w-]*)', log_json, name='log_json_view'),
        re_path(r'^', log_viewer, name='log_file_view'),
    ]
else:
    from django.conf.urls import url
    urlpatterns = [
        url(r'^json/(?P<file_name>[\.\w-]*)/(?P<page>[0-9]+)', log_json, name='log_json_view'),
        url(r'^json/(?P<file_name>[\.\w-]*)', log_json, name='log_json_view'),
        url(r'^', log_viewer, name='log_file_view'),
    ]

log_viewer/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
from itertools import islice
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.contrib.auth.decorators import (login_required, user_passes_test)
from django.contrib.admin.utils import (quote, unquote)
from django.utils.decorators import method_decorator
from log_viewer import settings
from log_viewer.utils import (readlines_reverse, JSONResponseMixin)


class LogJsonView(JSONResponseMixin, TemplateView):

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(LogJsonView, self).dispatch(*args, **kwargs)

    def get_log_json(self, file_name=None, page=1):
        context = {}

        # Clean the `file_name` to avoid relative paths.
        file_name = unquote(file_name).replace('/..', '').replace('..', '')
        file_urls = []
        file_names = []
        file_display = []
        page = int(page)
        current_file = file_name

        lines_per_page = settings.LOG_VIEWER_MAX_READ_LINES
        context['original_file_name'] = file_name
        context['next_page'] = page + 1
        context['log_files'] = []

        len_logs_dir = len(settings.LOG_VIEWER_FILES_DIR)

        for root, _, files in os.walk(settings.LOG_VIEWER_FILES_DIR):
            tmp_names = list(filter(lambda x: x.find('~') == -1, files))
            # if LOG_VIEWER_FILES is not set in settings
            # then all the files with '.log' extension are listed
            if len(settings.LOG_VIEWER_FILES) > 0:
                tmp_names = list(filter(lambda x: x in settings.LOG_VIEWER_FILES, tmp_names))
            else:
                tmp_names = [name for name in tmp_names if (name.split('.')[-1]) == 'log']

            file_names += tmp_names
            file_display += [('%s/%s' % (root[len_logs_dir:], name))[1:] for name in tmp_names]
            file_urls += list(map(lambda x: '%s/%s' % (root, x), tmp_names))

        for i, element in enumerate(file_display):
            context['log_files'].append({
                quote(element): {
                    'uri': file_urls[i],
                    'display': element,
                }
            })

        if file_name:
            try:
                file_log = os.path.join(settings.LOG_VIEWER_FILES_DIR, file_name)
                with open(file_log, encoding='utf8', errors='ignore') as file:
                    next_lines = list(islice(readlines_reverse(file, exclude='Not Found'),
                                             (page - 1) * lines_per_page,
                                             page * lines_per_page))

                    if len(next_lines) < lines_per_page:
                        context['last'] = True
                    else:
                        context['last'] = False
                    context['logs'] = next_lines
                    context['current_file'] = current_file
                    context['file'] = file

            except Exception as error:
                print(error)
                pass
        else:
            context['last'] = True

        if len(context['log_files']) > 0:
            context['log_files'] = sorted(context['log_files'],
                                          key=lambda x: sorted(x.items()))

        return context

    def render_to_response(self, context, **response_kwargs):
        log_json = self.get_log_json(context.get('file_name'),
                                     context.get('page', 1))
        print(log_json)

        if 'file' in log_json:
            log_json['file'] = log_json['file'].name

        if 'view' in context:
            del context['view']

        context.update(**log_json)
        return self.render_to_json_response(context, **response_kwargs)


class LogViewerView(TemplateView):
    """
    LogViewerView class

    :cvar template_name: Name of the HTML template used to render the log files

    """
    template_name = "log_viewer/logfile_viewer.html"

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(LogViewerView, self).dispatch(*args, **kwargs)

    def get_context_data(self, file_name=None, page=1, **kwargs):
        """
        Read and return log files to be showed in admin page

        :param file_name: log file name
        :param page: log viewer page
        """
        context = super(LogViewerView, self).get_context_data(**kwargs)
        context['custom_file_list_title'] = settings.LOG_VIEWER_FILE_LIST_TITLE
        context['custom_style_file'] = settings.LOG_VIEWER_FILE_LIST_STYLES
        context['page_length'] = settings.LOG_VIEWER_PAGE_LENGTH
        return context


log_json = LogJsonView.as_view()
log_viewer = LogViewerView.as_view()

log_viewer/templates/log_viewer/logfile_viewer.html
{% extends "admin/base_site.html" %}
{% load admin_static i18n %}

{% block breadcrumbs %}
  <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    &rsaquo;
    <a href="{% url 'log_viewer:log_file_view' %}">{% if custom_file_list_title %}{{ custom_file_list_title }}{% else %}{% trans 'Log Viewer' %}{% endif %}</a>
  </div>
{% endblock %}

{% block extrastyle %}
  <link rel="stylesheet" type="text/css" href="{% static 'admin/css/changelists.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'log_viewer/css/jquery.dataTables.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'log_viewer/css/log-viewer.css' %}">

  {% if custom_style_file %}
    <link type="text/css" href="{{ custom_style_file }}" rel="stylesheet">
  {% endif %}
{% endblock %}

{% block extrahead %}
  <script src="{% static 'log_viewer/js/jquery.min.js' %}"></script>
  <script src="{% static 'log_viewer/js/jquery.dataTables.min.js' %}"></script>
{% endblock %}

{% block content %}
  <div class="django__log__viewer">
    <div id="content-main">
      <div class="module filtered" id="changelist">
        <div id="changelist-filter">
          <h2>{% trans 'Log Files' %}</h2>
          <div id="log-files-list">
            <!-- <ul><li><a class="btn-load-json-log" href="javascript:;" data-href="/admin/log_viewer/json/default.log">default.log</a></li></ul> -->
          </div>
        </div>
        <form id="changelist-form">
          <div class="results">
            <table id="log-entries" class="display" style="width:100%">
              <thead>
                <tr>
                  <th scope="col">{% trans 'No.' %}</th>
                  <th scope="col">{% trans 'Log entries' %}</th>
                </tr>
              </thead>
              <tbody>
                <tr><td colspan="2">{% trans 'No entries!' %}</td></tr>
              </tbody>
            </table>
          </div>
        </form>
      </div>
    </div>
  </div>

  <script>
    function loadDataTable(table_name, url_json) {
      $(table_name).DataTable({
        pageLength: '{{ page_length }}',
        columns: [{data: 0}, {data: 1}],
        ajax: function (data, callback, settings) {
          $.ajax({
            type: 'get',
            url: url_json,
            success:function(response){
                const new_logs = [];
                var next_page = response.next_page || 1;

                response.logs.forEach(function(text, numb, logs){
                  new_logs.push([numb+1, text])
                });

                callback({
                  data: new_logs,
                  recordsTotal: next_page,
                  recordsFiltered: next_page
                });
            }
          });
        }
      });
    }

    function loadDataTableTrigger(url_json) {
      var table_name ='table#log-entries';
      if (!$.fn.dataTable.isDataTable(table_name)) {
        loadDataTable(table_name, url_json);
      }else {
        table_dt = $(table_name).DataTable();
        table_dt.destroy();
        loadDataTable(table_name, url_json);
      }
    }
    $(document).ready(function() {
        // just blank entry to get the `log_files`
        var url_json = "{% url 'log_viewer:log_json_view' xxxxx %}";
        $.getJSON(url_json, function(result){
            result.log_files.forEach(function(log) {
                const keys = Object.keys(log);
                Object.entries(log).forEach(([file_name, xtra]) => {
                    // console.log(file_name);
                    // console.log(xtra);
                    var html = '<ul><li><a class="btn-load-json-log" href="javascript:;" '+
                               'data-href="'+url_json+file_name+'">'+xtra.display+'</a></li></ul>'
                    $('div#log-files-list').append(html);
                });
            });
        });
    });

    $(document).on('click', '.btn-load-json-log', function(){
        // console.log(this);
        alert("High");
        $(this).closest('#log-files-list').find('li').removeClass('selected');
        $(this).closest('li').addClass('selected');
        loadDataTableTrigger($(this).data('href'));
    });
  </script>
{% endblock%}